const H = (character: string) => character.repeat(64)

export function providerRunFixture() {
  return {
    contract: 'insurance-v5-provider-trial-run.v2',
    run_id: 'v5-trial-20260817',
    run_sha256: H('d'),
    catalog_id: 'insurance-product-schema-v5',
    catalog_sha256: H('a'),
    status: 'COMPLETED',
    provider: {
      family: 'qwen',
      base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      model: 'qwen-plus',
      mode: 'streaming-non-thinking-json',
    },
    call_count: 1,
    started_at: '2026-08-17T12:00:00Z',
    finished_at: '2026-08-17T12:01:00Z',
    serving_effect: 'NONE',
    review_publish_admission: false,
    products: [{
      product_id: '596',
      product_version_id: '596-1',
      product_display_name: '平安e生保（尊享版）医疗保险',
      insurance_class: '医疗险',
      schema_id: 'insurance-product-schema-v5:医疗险',
      source_revision_id: 'source-medical-596-1',
      source_manifest_sha256: H('e'),
      status: 'REVIEW_REQUIRED',
      error_code: 'EVIDENCE_REVIEW_REQUIRED',
      files: [{ file_name: '保险条款.pdf', sha256: H('f'), page_count: 1 }],
      attempts: [{
        attempt: 1,
        outcome: 'PRESERVED',
        response_id: 'chatcmpl-trial-1',
        response_model: 'qwen-plus',
        finish_reason: 'stop',
        prompt_tokens: 100,
        completion_tokens: 20,
        total_tokens: 120,
        error_code: 'EVIDENCE_REVIEW_REQUIRED',
      }],
      preview: {
        contract: 'insurance-v5-candidate-preview.v2',
        catalog_id: 'insurance-product-schema-v5',
        catalog_sha256: H('a'),
        schema_id: 'insurance-product-schema-v5:医疗险',
        source_revision_id: 'source-medical-596-1',
        insurance_class: '医疗险',
        product_id: '596',
        product_version_id: '596-1',
        product_display_name: '平安e生保（尊享版）医疗保险',
        serving_effect: 'NONE',
        review_publish_admission: false,
        categories: [{ ordinal: 0, category_id: '02', display_name: '产品主数据' }],
        fields: [{
          ordinal: 0,
          category_id: '02',
          category_display_name: '产品主数据',
          field_id: 'product_name',
          display_name: '险种名称',
          knowledge_role: '事实 Fact',
          formation_modes: ['原文抽取'],
          output_kind: 'Fact',
          state: 'present',
          value: '平安e生保（尊享版）医疗保险',
          evidence: [{
            source_revision_id: 'source-medical-596-1',
            verification_status: 'UNRESOLVED',
            verification_error: 'V5_EVIDENCE_PAGE_NOT_FOUND',
            locator: 'pdf:保险条款.pdf#page=1',
            quote: '平安e生保（尊享版）医疗保险',
          }],
        }],
        preview_sha256: H('b'),
      },
    }],
  }
}
